name: Build, Test, and Publish to GHCR

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET 9.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Run unit tests
      run: dotnet test --no-build --verbosity normal

    - name: Publish app
      run: dotnet publish -c Release -o out

    - name: Log in to GHCR
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository_owner }}/taskmanagerapi:latest .

    - name: Push Docker image
      run: docker push ghcr.io/${{ github.repository_owner }}/taskmanagerapi:latest
